image: node:18
stages:
  - checks
before_script:
  - npm install

tests:
  stage: checks
  only:
    - main
    - merge_requests
  script:
    - npm run test

linting:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - npm run lint

type-checking:
  stage: checks
  only:
    - main
    - merge_requests
  script:
    - npm run tsc