stages:
  - checks
before_script:
  - npm install
tests:
  stage: checks
  only:
    - main
    - merge_requests
  script:
    - npm run test
type-checking:
  stage: checks
  only:
    - main
    - merge_requests
  script:
    - npm run tsc